const layout = [
    {
        w: 27,
        h: 402,
        x: 92,
        y: 13,
        i: '0',
        moved: true,
        static: true,
    },
    {
        w: 17,
        h: 133,
        x: 1,
        y: 459,
        i: '1',
        moved: true,
        static: true,
    },
    {
        w: 6,
        h: 409,
        x: 36,
        y: 9,
        i: '2',
        moved: true,
        static: true,
    },
    {
        w: 5,
        h: 409,
        x: 58,
        y: 9,
        i: '3',
        moved: true,
        static: true,
    },
    {
        w: 5,
        h: 409,
        x: 64,
        y: 9,
        i: '4',
        moved: true,
        static: true,
    },
    {
        w: 83,
        h: 111,
        x: 36,
        y: 478,
        i: '5',
        moved: true,
        static: true,
    },
    {
        w: 21,
        h: 229,
        x: 1,
        y: 10,
        i: '6',
        moved: true,
        static: true,
    },
];

export default layout;
